spring:
  datasource:
    url: jdbc:tc:postgresql:16-alpine:///jurisfacil_test
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
