package com.jurisfacil.audit.model;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    MEMBER_INVITED,
    MEMBER_ACCEPTED,
    MEMBER_DEACTIVATED,
    MEMBER_ROLE_CHANGED,
    OWNERSHIP_TRANSFERRED,
    PROCESS_CREATED,
    PROCESS_UPDATED,
    PROCESS_SUSPENDED,
    PROCESS_REACTIVATED,
    PROCESS_CLOSED,
    MOVEMENT_ADDED,
    ORGANIZATION_CREATED,
    ORGANIZATION_SUSPENDED,
    ORGANIZATION_ACTIVATED,
    ORGANIZATION_DEACTIVATED,
    ENTITLEMENT_CHANGED,
    PLAN_CHANGED,
    PASSWORD_RESET
}
